### ISSUE TITLE
H2 data in the base data file

### ISSUE THREAD

**Issue by nhniina** [TradeRES/TradeRES-Backbone-demo#19]
Deleted general H2 node with price 65 €/MWh and removed H2 units from uGroup and p_groupPolicyUnit. Trying to keep all H2 data in H2 file (except related to VRE limit?).

**Comment by SilkeJo** [comment]
makes sense, just that for the market design runs I did not want the industrial H2 demand time series (currently). 
Therefore I did not use the H2-file. Also I do not like that it includes a seperate storage unit. I would prefer to add storage costs to electrolyser / turbine investment costs.
