### ISSUE TITLE
Transmission capacities

### ISSUE THREAD

**Issue by nhniina** [TradeRES/TradeRES-Backbone-demo#2]
Transmission capacities are based on ENTSO-E 2030 data. 2040/2050 transmission capacities have not been added yet for S1-S4. Currently they also use 2030 capacities.

**Comment by nhniina** [comment]
Update also the availability of PT-ES connection (and maybe some others?) to a time series form. Data from LNEG? Different capacities to different directions?

**Comment by SilkeJo** [comment]
I added 2050 tranmission capacities. BUT: PT-ES connection is not dynamic, yet

**Comment by nhniina** [comment]
Slightly different regions in Backbone and COMPETES so I changed connections to SK to go to BK and removed SK-BK connections.
